name: CI Build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  amd64_windows_gcc:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: windows-2016
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        install: make cmake mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
    - run: which mingw32-make
    - run: cmake -B build -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - run: cmake --build build --config $BUILD_TYPE
    - uses: actions/upload-artifact@v2
      with:
        name: build-amd64_windows_gcc
        path: "build/*"
    - run: build/unit_tests

  amd64_linux_gcc:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y make gcc cmake libasound2-dev libjack-jackd2-dev libpulse-dev pkg-config
    - run: cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - run: cmake --build build --config $BUILD_TYPE
    - run: tar caf build.tar.gz build
    - uses: actions/upload-artifact@v2
      with:
        name: build-amd64_linux_gcc
        path: "*.tar.gz"
    - run: build/unit_tests
