name: CI Build

on: [push, pull_request]

jobs:
  build-win-msvc:
    name: Windows VS ${{ matrix.os }} ${{matrix.platform}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, windows-2019]
        platform: [Win32, x64]
    steps:
    - uses: actions/checkout@v2
    - name: Get version tag
      run: |
        git_tag=$(git describe --always --tags --dirty)
        echo "GIT_TAG=${git_tag}" >> ${GITHUB_ENV}
      shell: bash

    # Install dependencies
    # libsoundio can't build with CMake 3.18 https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1363
    - run: choco install cmake --version=3.17.5 -y --no-progress
    # Install virtual audio device (Test will fail without this, because there are no sound device on CI build machine)
    - run: choco install voicemeeter -y --no-progress

    # Build
    - run: cmake --version
    - run: cmake -B build -A ${{matrix.platform}} -DCMAKE_BUILD_TYPE=Release
    - run: cmake --build build --config Release

    # Upload artifact
    - uses: actions/upload-artifact@v2
      with:
        name: libsoundio-${{ env.GIT_TAG }}-windows-${{ matrix.platform }}
        path: "build/*"

    # Test
    - name: Run tests
      run: |
        cd build/Release
        ./unit_tests
        ./sio_list_devices

  build-win-mingw:
    name: Windows MinGW x64
    runs-on: windows-2016
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - name: Get version tag
      run: |
        git_tag=$(git describe --always --tags --dirty)
        echo "GIT_TAG=${git_tag}" >> ${GITHUB_ENV}

    # Install dependencies
    - uses: msys2/setup-msys2@v2
      with:
        install: make cmake mingw-w64-x86_64-make mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc
    - run: choco install voicemeeter -y --no-progress
      shell: powershell

    # Build
    - run: cmake --version
    - run: cmake -B build -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release
    - run: cmake --build build --config Release

    # Upload artifact
    - uses: actions/upload-artifact@v2
      with:
        name: libsoundio-${{ env.GIT_TAG }}-mingw64
        path: "build/*"

    # Test
    - name: Run tests
      run: |
        cd build
        ./unit_tests
        ./sio_list_devices

  build-ubuntu:
    name: Ubuntu GCC
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Get version tag
      run: |
        git_tag=$(git describe --always --tags --dirty)
        echo "GIT_TAG=${git_tag}" >> ${GITHUB_ENV}

    # Install dependencies
    - run: sudo apt install -y libasound2-dev libjack-jackd2-dev libpulse-dev

    # Build
    - run: cmake --version
    - run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    - run: cmake --build build --config Release

    # Upload artifact
    - run: tar cf build.tar build
    - uses: actions/upload-artifact@v2
      with:
        name: libsoundio-${{ env.GIT_TAG }}-ubuntu
        path: "*.tar"

    # Test
    - name: Run tests
      run: |
        cd build
        ./unit_tests
        ./sio_list_devices

  build-macos:
    name: macOS Clang
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2

    # Build
    - run: cmake --version
    - run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    - run: cmake --build build --config Release

    # Upload artifact
    - run: tar cf build.tar build
    - uses: actions/upload-artifact@v2
      with:
        name: libsoundio-${{ env.GIT_TAG }}-macos
        path: "*.tar"

    # Test
    - name: Run tests
      run: |
        cd build
        ./unit_tests
        ./sio_list_devices
