name: CI Build

on: [push, pull_request]

jobs:
  amd64_windows_msvc:
    runs-on: windows-2016
    steps:
    - run: choco install cmake --version=3.17
    - uses: actions/checkout@v2
    - run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_PULSEAUDIO=OFF -DENABLE_COREAUDIO=OFF
    - run: cmake --build build --config Release --verbose
      continue-on-error: true
    - uses: actions/upload-artifact@v2
      with:
        name: build-amd64_windows_msvc
        path: "build/*"
    - run: build/unit_tests

  amd64_windows_gcc:
    runs-on: windows-2016
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        install: make cmake mingw-w64-x86_64-make mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc
    - run: which mingw32-make
    - run: cmake -B build -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DENABLE_PULSEAUDIO=OFF -DENABLE_COREAUDIO=OFF
    - run: cmake --build build --config Release
    - uses: actions/upload-artifact@v2
      with:
        name: build-amd64_windows_gcc
        path: "build/*"
    - run: build/unit_tests

  amd64_linux_gcc:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y libasound2-dev libjack-jackd2-dev libpulse-dev
    - run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_COREAUDIO=OFF
    - run: cmake --build build --config Release
    - run: tar caf build.tar.gz build
    - uses: actions/upload-artifact@v2
      with:
        name: build-amd64_linux_gcc
        path: "*.tar.gz"
    - run: build/unit_tests

  macos:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_PULSEAUDIO=OFF
    - run: cmake --build build --config Release
    - run: tar caf build.tar.gz build
    - uses: actions/upload-artifact@v2
      with:
        name: build-macos
        path: "build/*"
    - run: build/unit_tests
