name: amd64_linux_gcc

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:

  amd64_linux_gcc:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y make gcc cmake
    - run: cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - run: cmake --build build --config $BUILD_TYPE
    - run: file build/unit_tests
    - run: build/unit_tests
