name: amd64_windows_gcc

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: windows-2016
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
    - run: cmake -B build -G"MSYS Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - run: cmake --build build --config $BUILD_TYPE
    - run: file build/unit_tests.exe
    - run: build/unit_tests
